### ISSUE TITLE
Separate Web Client and Configuration UI

### ISSUE THREAD

**Issue by leonsmith** [MediaBrowser/MediaBrowser#972]
I'm not sure how well this suggestion is going to go down as It's probably not a small job but if feels like the web client and web configuration ui should be split and installable as separate applications.

That should allow the development of the web interface and UI to be uncoupled and progress separately in a similar manage to how the other clients applications do at the moment.

**Comment by LukePulverenti** [comment]
This won't happen for the existing web client because it is a great tool to use to preview what the library will look like in other clients. When users asking questions or having problems, we always point them to the web client to see how it looks there first before troubleshooting the client they're using. If we introduce an extra step of a separate install, it will only make that harder.

We do hope to have a second web client in the future designed for TV usage, and this will probably what you're suggesting.

**Comment by leonsmith** [comment]
Thats what I expected just wanted your thoughts on it.

A web client for big screen is exactly what sparked my interest in looking into it as the MBTheatre doesn't appear to be supported on linux (I haven't actually tried running it with mono thought so am not 100% sure)
